# Site settings
title: Taylor Brown
email: t@ylorbrown.com
description: > # this means to ignore newlines until "baseurl:"
  Taylor Brown is an SEO Specialist for Tribune Publishing. He's also an improviser and makes independent comedy videos for the internet.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://taylorcbrown.com" # the base hostname & protocol for your site
twitter_username: tcbrown
github_username:  taylorcbrown

# Build settings
markdown: kramdown
